-- AlterTable
ALTER TABLE "table_uuid" ALTER COLUMN "series" SET DATA TYPE VARCHAR(255),
ALTER COLUMN "invoice" SET DATA TYPE VARCHAR(255),
ALTER COLUMN "fiscal_folio_uuid" SET DATA TYPE VARCHAR(255);
